{% set name = "metaknowledge" %}
{% set version = "3.3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0bdd5fa6e96aee866c9607622157c41a3933db00e5341ba319226dc96698f8fa

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - metaknowledge = metaknowledge.bin:mkCLI
    - metaknowledge-mdToNb = metaknowledge.bin:mkMdToNb
    - metaknowledge-DocsGen = metaknowledge.bin:mkDocs

requirements:
  host:
    - python
    - pip
  run:
    - python
    - networkx >=2.0
    - pyreadline  # [win]
    - matplotlib-base
    - scipy
    - numpy

test:
  imports:
    - metaknowledge
    - metaknowledge.tests
  commands:
    - metaknowledge --help

about:
  home: https://github.com/networks-lab/metaknowledge
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python library for doing bibliometric and network analysis in science and health policy research

  description: |
    metaknowledge is a Python3 library that simplifies bibliometric research using data
    from various sources. It reads a directory of plain text files containing meta-data
    on publications and citations, and writes to a variety of data structures that are
    suitable for quantitative, network, and text analyses. It handles large datasets
    (e.g. several million records) efficiently.
  doc_url: https://metaknowledge.readthedocs.io/
  dev_url: https://github.com/networks-lab/metaknowledge

extra:
  recipe-maintainers:
    - vtraag
