travis:
  secure:
    BINSTAR_TOKEN: zwE7PRe9YO3PJ6oMgJ/Z9foj6XOnXw0rMA11YIjCbdI7EFC7N28HJ0PbZzDDPn5sqT5kzsWXkiGnkb3n9hJU6nfNLwAVuoU2cy3RVJRMQ2CIoj7BqGKgGirPHQY+YC8x7GflcPDN3p8rnVISCIWlp/v4kcL7/I2e93AarqGxJ8G+FybWzKY7Iv3F4iWM3wLUyaViKUmkq9+2MHRm+1QyDMbZXInsCLAa03LYS1e4kfV+jXZzkNuH4fsIrfgRcZLdYDJvUf8ovDE59RHhj7nbimFG/3cjrZ80LvOANn7FbpUw5Dv1bJet00YByLuG1ZyW9125kC402lCrtXshR1ZOksUOS+9BUuYwqJXbLJjiKyqMbPu4B9jHKcRI1Ff/sX3+IcvBjw/192dkyjB/tX6rWnO6apuuWM/HFRyqIk73YrfK++EHutPHbdN38YAvLSJfwU5yW1Ky0XDTuyg4Um/0S1Qh40C1ErLQy1HnuYLTeS5uwv7w0IkiduvUy7Z72Br/eRIJRa04g6g9io6Lv2M2YeH6S5Iwh72l2IjB2KonLb48kES3MT3emUnox/qpcOKIvgunKmSHOlNwy3dGcBDRlrDIwkLgBNDPtD1ahTBxYrGdsK76g5otoUvLr9hqQLQQGMnYDu7+mhKxXg4BPuSazmsNrARIVsl4fwsmZSV5iT8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
